# .streamlit/secrets.toml 

[snowflake] 

user = "TDEWING19"

password = "Federals_20" 

account = "sba23770" 

warehouse = "COMPUTE_WH" 

database = "PETS" 

schema = "PUBLIC"

role = "ACCOUNTADMIN"
